### ISSUE TITLE
PictureUploadUseCase

### ISSUE THREAD

**Issue by AcGW-RErCotWd** [CSC207-2022F-UofT/course-project-macrosoft#52]
package PictureUploadUseCase
create FileDialogue -- for file selection, records the selected file as Path
enhance ReviewInteractor -- for filePath setting & updating, e.g. adding a filePath into Review.picPathList
enhance MenuItemInteractor

enhance UI for MenuItem

**Comment by inorrr** [comment]
Could potentially allow restaurant owners to add pictures when uploading their menu, but this feature takes further research (i.e. how does MongoDB saves images). I will come back and implemented this after the menu editing feature is completed and tested.

**Comment by AcGW-RErCotWd** [comment]
> 

The best practice to store images in DB is to store their Paths (URI), this issue can wait till further development, we will use a placeholder dummy pic for demo
