### ISSUE TITLE
Jlabel Multiline

### ISSUE THREAD

**Issue by xuallenx** [CSC207-2022F-UofT/course-project-macrosoft#97]
When using our add item feature in the menu,  adding descriptions longer than a certain length will result in overflow that stretches  the individual boxes for each item

**Comment by davidzylin** [comment]
I think using HTML for the labels or use JTextArea could potentially solve this problem

**Comment by inorrr** [comment]
Thank you for bringing this up!! That is definitely an issue and I'll try to fix it @xuallenx .  Thanks for the advice! @davidzylin
