### ISSUE TITLE
Implement current user singleton class

### ISSUE THREAD

**Issue by davidzylin** [CSC207-2022F-UofT/course-project-macrosoft#99]

**Comment by inorrr** [comment]
Does this class provide the functionality to save current user and current restaurant? Or there will be a separate class for current restaurant? I get if it's storing a ObjectId for the user/restaurant then we probably need only one.

**Comment by davidzylin** [comment]
We have changed the design, we are now storing a single user id in the controller, since it's not an entity, it doesn't violate the rules. However, we can use singleton for shopping cart.
